fix footer
skazzp/projectors-donuts pull request #11
Opened 2022-07-07 22:02 UTC by Remix007

2022-07-07 22:27 UTC, skazzp commented on src/partials/footer.html
> +        <div class="footer-social">
для чего див ?

2022-07-07 22:55 UTC, Remix007 commented on src/partials/footer.html
> +        <div class="footer-social">
ну так можна без, на всякий випадок

2022-07-08 06:11 UTC, skazzp requested changes
Давай див уберем

2022-07-08 06:57 UTC, skazzp approved these changes

2022-07-08 07:01 UTC, skazzp requested changes
проверяй, перед тем как пуллить. контейнер не закрыт, так не работает

2022-07-08 07:01 UTC, skazzp commented on src/partials/footer.html
> +    <div class="container">
див не закрывается.

2022-07-08 07:22 UTC, skazzp approved these changes

2022-07-08 08:13 UTC, skazzp approved these changes

2022-07-08 08:17 UTC, merged